import java.util.ArrayList;
import java.util.Map;

public class Automaton {
	
	public String input;
	private String state;
	private Map<String, String> rules; //<key: word, value: state>
	
	/* Runs the automaton given an input string of words
	 * @param game, the input game
	 * @param input, the input string of the automaton
	 * @return game, the new game suggestion(s) generated by the automaton
	 */
	private Game run(Game game, String input) {
		//TODO: filter input string to pull out keywords
		//TODO: parse input string
		//TODO: send input string through processing function
		//TODO: update game
		return game;
	}
	
	/* Finds new states given an input word
	 * @param word, the input word to the automaton
	 * @return states, the new state(s) found from the rules
	 */
	private ArrayList<String> findStates(String word) {
		ArrayList<String> states = new ArrayList<>();
		int offset = 1;
		while(rules.containsKey(word)) {
			states.add(rules.get(word));
			input = word + "_key" + offset;
			offset++;
		}
		return states;
	}
	
	/* Update the game given an action
	 * @param game, the input game
	 * @param action, the input action to take
	 * @return game, the updated game
	 */
	private Game update(Game game, Action action) {
		return game;
	}

}
